the-difference-engine/veterans-work

Makefile
https://trello.com/c/6F9Mi5GO/16-as-a-developer-i-want-a-makefile-to-both-learn-what-make-is-and-to-make-calling-common-commands-a-bunch-faster
this is a helpful addition to our lives, it allows you to just call `make _whatever_` to call common commands.
=> created makefile

Makefile
=> auto qa deploy

README.md
got some automation running, deploys to qa automatically build on heroku.
=> Heroku test

README.md
=> added workflow and deploy guides

db/migrate/20170210015933_add_fields_to_model.rb, db/schema.rb
=> Add Fields to Companies

Gemfile, Gemfile.lock, app/controllers/companies_controller.rb, db/seeds.rb
https://trello.com/c/bkck915v/23-add-in-faker-gem-seed-file
Added the Faker gem to gemfile. Created a seed file with faker and ran the seedfile.
=> Add faker gem and create seed file.

app/controllers/companies_controller.rb, app/views/companies/show.html.erb
Adding a company show page: https://trello.com/c/sBk9DoCx/24-create-a-company-show-page
=> Creating show page

app/models/company.rb, app/views/companies/index.html.erb, app/views/companies/show.html.erb
Completing this Trello card: https://trello.com/c/UKZszu7x/27-shorten-zip-code-to-5-digits-company-model
=> Created shorten_zip_code method

app/controllers/Companies/confirmations_controller.rb, app/controllers/Companies/omniauth_callbacks_controller.rb, app/controllers/Companies/passwords_controller.rb, app/controllers/Companies/registrations_controller.rb, app/controllers/Companies/sessions_controller.rb, app/controllers/Companies/unlocks_controller.rb, app/controllers/companies_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/routes.rb
https://trello.com/c/wYr0rRoq
* Add devise exceptions for Companies registration form
* Add Companies edit fields
* Merged devise registration controller with Companies controller
=> Companies crud forms

app/views/layouts/application.html.erb
https://trello.com/c/npXAKiCk/31-add-a-sign-out-link-for-devise
Added link to logout path for companies in the application html, once they are logged in.
=> Add logout link to application html if a company is logged in.

db/seeds.rb
https://trello.com/c/VfQKiEf6/41-create-seed-file-for-service-category-model
Added an each loop to the seed file for ServiceCategory to create services.
=> Add each loop to seed file for service_category

Makefile, app/controllers/customer_requests_controller.rb, app/models/company.rb, app/models/customer_request.rb, app/views/customer_requests/index.html.erb, app/views/customer_requests/new.html.erb, config/routes.rb, db/migrate/20170220221738_add_service_categor_id_to_customer_requests.rb, db/migrate/20170221001715_remove_fields_from_customer_request.rb, db/migrate/20170221003023_remove_more_fields_from_customer_request.rb, db/migrate/20170221003235_add_customer_id_to_customer_requests.rb, db/schema.rb, spec/examples.txt
https://trello.com/c/xQjbgCaU/39-refactor-customer-request
passign off driving to someone else
=> Create customer request

app/controllers/customer_requests_controller.rb, app/views/customer_requests/index.html.erb, config/routes.rb
trello story: https://trello.com/c/n1aIdbUi/35-customer-request-table
Please approve!
=> Edited customer requests index

app/controllers/customer_requests_controller.rb, app/views/customer_requests/new.html.erb, db/migrate/20170221011838_add_expires_date_to_customer_requests.rb, db/schema.rb, spec/examples.txt
https://trello.com/c/FYxxfcgB/10-customer-can-set-an-expiration-date-on-requests
=> added field to this thang

app/controllers/companies/registrations_controller.rb
added address-related attributes to new page for companies and also added corresponding keys to controller 
related to: https://trello.com/c/1N7lduNW/42-company-can-add-service-categories-during-sign-up-process
=> added attributes to new page for companies

app/views/companies/registrations/new.html.erb
Wild and crazy change
https://trello.com/c/BFZgVqkN
=> Minor form order change

app/controllers/companies/registrations_controller.rb, app/controllers/companies_controller.rb
this takes care of the signup problem with companies and not existing yet inside the create method
=> Company sign up create services

Gemfile, Gemfile.lock, app/assets/javascripts/app.js, app/assets/javascripts/application.js, app/assets/javascripts/controllers/test.js, app/views/layouts/application.html.erb
https://trello.com/c/v0fWLKlZ/47-installing-angularjs
* installed using gem wrapper 
* left test controller and built app.js
* removed turbolinks
=> Install angular

app/assets/stylesheets/_backgrounds.css.scss, app/views/layouts/application.html.erb
=> fixed bottom of page

app/controllers/quotes_controller.rb, app/models/quote.rb, app/views/quotes/show.html.erb
- Fix style on Quote show view
- Add Rspec tests for Quote controller
https://trello.com/c/z5VlcbrE
=> Style company quote show

app/controllers/quotes_controller.rb, app/models/quote.rb, app/views/quotes/show.html.erb
- Add Customer email and Company name to Quote show page, and add buttons
- Add buttons for Current Company
- Change routes for quote show buttons
=> Add quotes show page

app/views/companies/registrations/edit.html.erb
Review needed for https://trello.com/c/hcis8CHX/53-styled-company-devise-views
- Styled Company Edit page using bootstrap.
=> Styled Company Edit page with bootstrap

app/views/companies/registrations/edit.html.erb, app/views/companies/registrations/new.html.erb
Bootstrap styling on company edit page.
=> Style company login

app/views/companies/registrations/edit.html.erb, app/views/companies/registrations/new.html.erb, app/views/companies/sessions/new.html.erb, app/views/customers/sessions/new.html.erb
https://trello.com/c/VUJNXcDf/57-company-sign-in-style
- Styled Company login page to reflect Customer login page. 
- Shifted login button before forgot password link on Customer sign In page.
=> Company sign in style

app/mailers/application_mailer.rb, app/mailers/company_mailer.rb, app/models/company.rb, app/models/contract.rb, app/models/customer.rb, app/models/customer_request.rb, app/models/quote.rb, app/models/role.rb, app/views/company_mailer/company_mailer.html.erb, app/views/layouts/mailer.html.erb, app/views/quotes/index.html.erb, db/migrate/20170323231548_create_contracts.rb, db/migrate/20170323231700_add_contract_columns.rb, db/schema.rb, spec/factories/companies.rb, spec/factories/contracts.rb, spec/factories/customer_requests.rb, spec/factories/customers.rb, spec/factories/roles.rb, spec/models/company_spec.rb, spec/models/customer_request_spec.rb, spec/models/customer_spec.rb, spec/models/role_spec.rb, spec/spec_helper.rb
-Create Contract model for quote/customer_request join table
- Create company mailer for rejection purposes
- Add logic to quotes index page
https://trello.com/c/z5VlcbrE
=> Add Contract model

app/controllers/quotes_controller.rb, app/models/quote.rb, app/views/customers/show.html.erb, app/views/quotes/new.html.erb, spec/models/quote_spec.rb
https://trello.com/c/fAY36idi
-Style page to look like other form views
-Form can generate quote and store to the database
=> New quotes

app/models/admin.rb, config/routes.rb, db/migrate/20170327234409_devise_create_admins.rb, db/schema.rb, spec/factories/admins.rb, spec/models/admin_spec.rb
=> admin model

app/views/customer_requests/index.html.erb, app/views/customer_requests/new.html.erb, spec/spec_helper.rb
https://trello.com/c/fBE7RJfh/64-stylize-company-request-view
- Used bootstrap to format page for readability and consistency 
- Using class "form-control" in the input fields
Expiration Date and Select Type of Work may need a slight tweaking for appearance, but works for now.
=> Styled Company Work Request View to match other pages

app/views/companies/registrations/edit.html.erb, app/views/quotes/index.html.erb, app/views/quotes/show.html.erb
https://trello.com/c/BB5I4BoR
-Style customer quotes index page.
-Add more functionality to index page.
-Style customer quotes show page.
=> Customer quotes index and show

app/views/customer_requests/new.html.erb
https://trello.com/c/fBE7RJfh/64-stylize-customer-request-view
- Styled the Customer Work Request to include a drop-down calendar menu selection
=> Customer Request styled

app/views/customers/show.html.erb, app/views/layouts/application.html.erb
No Trello card...
- Styled Customer landing page/ Home page.
-Moved links into application.html.erb to clean up page.
=> Style customer landing page and organize links.

app/assets/stylesheets/quotes.scss, app/views/quotes/index.html.erb
https://trello.com/c/1G6J9HsU
- Added Customer Request customer email and description to Quotes Index view
- Added CSS to qoutes.scss file to make new info stand out
=> Add CustomerRequest email and description to Quotes Index view

app/models/company.rb, db/migrate/20170407004950_add_status_to_company_model.rb, db/schema.rb, spec/factories/companies.rb, spec/models/company_spec.rb
https://trello.com/c/apKYIx2q
- Added Status attribute to Company model with a default of Pending.
=> Add status with default pending to company model

app/views/quotes/index.html.erb, app/views/quotes/show.html.erb
- Removed email and extra description from Quotes Index view
- Fixed Quote ID format 
- Added Back button to Quotes Show view
=> Format quotes index

app/controllers/companies_controller.rb, app/controllers/customers_controller.rb, app/views/layouts/application.html.erb, spec/controllers/companies_controller_spec.rb, spec/controllers/customers_controller_spec.rb
https://trello.com/c/EIs1WaWL
- Added if statement to show method for companies controller.
- Added before_action authenticate_company! to companies controller.
- Added if statement to show method for customers controller.
- Added before_action authenticate_customer! to customer controller.
- Added Profile link to my Account Drop Down in application.html.erb for companies.
=> Disable public visibility

app/controllers/quotes_controller.rb, spec/controllers/quotes_controller_spec.rb, spec/factories/quotes.rb
https://trello.com/c/P194Boje
This handles blank values or empty strings if nothing else we build in doesn't
=> handles when a company leaves blank values in a quote price

app/assets/javascripts/admins.js, app/assets/javascripts/contracts.coffee
=> Clear js comment issue

app/controllers/companies/registrations_controller.rb
https://trello.com/c/PNAOG8tc
-Fix bug in companies registrations controller for company services.
=> Fix Bug in companies registraions controller.

app/views/quotes/_customer_quotes.html.erb, app/views/quotes/show.html.erb
- Updated Customer Quotes Index view
- Removed Accept and Decline buttons from Accepted Quotes Show view
=> Fix quotes controller

app/controllers/customer_requests_controller.rb, spec/controllers/customer_requests_controller_spec.rb
https://trello.com/c/rfPZtvWj
- In the customer requests controller change the check status for companies from approved to active.
=> Change checking the company status of approved to active.

app/controllers/customer_requests_controller.rb
now it's "insufficient privileges" in line 72
=> fixing spelling error in customer_requests_controller

app/controllers/companies_controller.rb, app/models/customer_request.rb, spec/controllers/companies_controller_spec.rb, spec/controllers/customers_controller_spec.rb, spec/controllers/pages_controller_spec.rb, spec/controllers/quotes_controller_spec.rb, spec/models/customer_request_spec.rb
Just felt like doing some maintenance. No story related to this.
=> suite and individual tests runningnow

app/models/customer.rb, spec/controllers/customers_controller_spec.rb
https://trello.com/c/oZI69NLq
- Modify validations for customer to allow cascading destroy for reviews and customer requests.
- Create Rspec test to check if cascading is occurring upon destroying a customer.
=> Testing for cancelled customers

Gemfile, Gemfile.lock, app/assets/javascripts/app.js, app/assets/javascripts/application.js, app/assets/javascripts/components.js, app/assets/javascripts/components/post.jsx, app/assets/javascripts/components/review.jsx, app/assets/javascripts/controllers/test.js, app/assets/javascripts/server_rendering.js, app/controllers/companies_controller.rb, app/controllers/reviews_controller.rb, app/views/companies/show.html.erb, app/views/pages/how.html.erb, config/initializers/react_server_rendering.rb, config/routes.rb
Installing a single react component for exploration and possible implementation
=> react_js test

app/controllers/companies/registrations_controller.rb
https://trello.com/c/zm0Eyzx7
* replaced alll dem mentions
=> replaced mentions per story

app/controllers/companies/registrations_controller.rb
Reverts the-difference-engine/veterans-work#225
=> Revert "replaced mentions per story"

app.json, app/controllers/companies/registrations_controller.rb, app/views/companies/show.html.erb, db/seeds.rb
https://trello.com/c/zm0Eyzx7
* changeed the thing
=> lets try that again

app/assets/stylesheets/quotes.scss, app/views/quotes/show.html.erb
-change panel class to panelQuotes
- move the deny button outside the form
=> Fixed issues

app/controllers/application_controller.rb, app/views/admins/shared/_links.html.erb, config/routes.rb
this removes the ability to create admins through the ui
https://trello.com/c/FnF14xBs
=> Remove admin signup

Gemfile, Gemfile.lock, Makefile, app/views/admins/index.html.erb, db/seeds.rb
=> seeded and ready to develop

app/assets/stylesheets/_colors.scss, app/assets/stylesheets/pages.scss, app/assets/stylesheets/quotes.scss, app/models/company.rb, app/views/companies/registrations/edit.html.erb, app/views/companies/registrations/new.html.erb, app/views/companies/sessions/new.html.erb, app/views/customers/registrations/edit.html.erb, app/views/customers/registrations/new.html.erb, app/views/customers/sessions/new.html.erb, app/views/customers/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/_contact_info.html.erb, app/views/pages/about.html.erb, app/views/pages/how.html.erb, app/views/pages/index.html.erb, app/views/quotes/_company_quotes.html.erb, app/views/quotes/_customer_quotes.html.erb, app/views/reviews/new.html.erb, spec/controllers/companies_controller_spec.rb, spec/controllers/customer_requests_controller_spec.rb, spec/factories/companies.rb
-Contact information partial
-Responsiveness Tag
-Responsive adjustments to text and tables
-Phone number and zip code validation to company
-Added uniform logo color to buttons
-Uniform text capitalization
=> Partial responsive button styling

app/controllers/quotes_controller.rb, spec/controllers/quotes_controller_spec.rb
Wrote two patch tests in quotes_controller_rspec.rb file.
=> improve test coverage for quotes controller

Makefile, app/controllers/api/v1/reviews_controller.rb, app/controllers/contracts_controller.rb, spec/controllers/api/v1/reviews_controller_spec.rb, spec/controllers/contracts_controller_spec.rb
Completed 90%+ coverage for all tests.
=> Improve test coverage

Gemfile, Gemfile.lock, app/controllers/companies/registrations_controller.rb, app/models/company.rb, spec/factories/companies.rb
added website validation
handled controller when no params
added to validation and factory
=> Updating validations

Gemfile, Gemfile.lock, app/controllers/companies/registrations_controller.rb, app/controllers/companies_controller.rb, app/models/company.rb, app/views/companies/registrations/edit.html.erb, app/views/companies/registrations/new.html.erb, app/views/companies/show.html.erb, db/migrate/20170706235608_add_attachment_avatar_to_companies.rb, db/schema.rb, spec/controllers/companies_controller_spec.rb, spec/factories/companies.rb, spec/models/company_spec.rb
https://trello.com/c/AYEQJhpT/112-paperclip-install
able to upload company profile photo
=> paperclip installed

Makefile, app/assets/stylesheets/images.css.scss
Scale mobile icons and created a "make j_dev" command (webpack)
=> Icons scale mobile

config/routes.rb
Reverts the-difference-engine/veterans-work#271
=> Revert "updated var"

app/views/customers/show.html.erb, spec/features/customer_spec.rb
https://trello.com/c/UnfxT3lW/122-feature-tests-customer-creates-work-request
=> test complete

app/views/customer_requests/new.html.erb, app/views/customers/show.html.erb, spec/controllers/customer_requests_controller_spec.rb, spec/features/customer_spec.rb
git pull and pushed back up a linted version
=> Feature tests

app/views/customer_requests/_company_customer_requests.html.erb, app/views/customer_requests/show.html.erb, spec/features/company_spec.rb, spec/features/customer_spec.rb
-Feature test for creating a quote from a company
-Feature test for accepting a quote from a customer
=> Feature test company login

app/controllers/contracts_controller.rb, spec/controllers/contracts_controller_spec.rb
Testing that our instance variable are being created the way we think they are. 
-Added test to check instance variables being created the expected way in contracts controller.
=> Further tests

app/controllers/contracts_controller.rb, app/controllers/customer_requests_controller.rb, app/controllers/quotes_controller.rb, package-lock.json, package.json
-quotes
-contracts
-requests ( added else statement )
=> Add error message

app/controllers/companies/registrations_controller.rb, app/views/companies/registrations/new.html.erb
https://trello.com/c/h2HQMddo/139-company-registration-bug-fields-remove-themselves
=> save service categories. check if they include in view

app/assets/stylesheets/company.scss, app/views/companies/registrations/edit.html.erb
when working on the paperclip, we wanted to make better instructions for the edit page on the current password.
=> added label for better instructions

Gemfile, app/models/company.rb
https://trello.com/c/bC6rkIa5/138-company-registration-remove-url-validation
=> removed validation for url

Gemfile.lock, app/controllers/customer_requests_controller.rb, app/models/customer_request.rb, app/models/quote.rb, spec/controllers/customer_requests_controller_spec.rb
https://trello.com/c/kfFBkpvo/136-add-validations-for-quotes-and-customer-requests
Added validations to make sure all fields are present when creating new requests and quotes
=> added more validations

app/controllers/customer_requests_controller.rb, spec/controllers/customer_requests_controller_spec.rb
Changes to the edit_customer_requests branch
=> Edit customer requests

app/controllers/customer_requests_controller.rb, app/models/customer_request.rb, app/views/customer_requests/_customer_customer_requests.html.erb, app/views/customer_requests/show.html.erb, spec/controllers/customer_requests_controller_spec.rb
story: https://trello.com/c/lBYG4rxW
* added button to delete request
* wrote tests for controller
* cleaned up trailiwags
=> Handle customer_request delete

app/assets/stylesheets/_navigation.scss, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, spec/features/pages_spec.rb
Most links are now tested. The search function doesn't do anything yet, so that does not have a test. 
https://trello.com/c/FNYMZ2a9/133-updated-veterans-work-homepage
=> Mainpage tests

app/assets/stylesheets/_colors.scss, app/assets/stylesheets/_navigation.scss, app/assets/stylesheets/pages.scss, app/views/layouts/application.html.erb, app/views/pages/index.html.erb, spec/controllers/orders_controller_spec.rb
-added more wording to the header
- same location for sign up and sign in
=> Edit homepage layout

app/views/customer_requests/show.html.erb, spec/features/company_spec.rb
=> tests done

app/models/company.rb, app/views/companies/show.html.erb, spec/models/customer_spec.rb
=> improved layout and added link to email

app/views/pages/how.html.erb
Fixed the issue of the photo being redic
=> fixed awful issue after merge with master
